image: eu.gcr.io/movici-develop/cicd-pipeline-tools:latest

stages:
- verify
- test
- deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.testing:
  stage: test

  only:
  - main
  - merge_requests

check_version_upgrade:
  stage: verify
  image: alpine/git
  only:
    refs:
    - merge_requests
    changes:
    - client/**/*
    - server/**/*
    - VERSION
  except:
    refs:
    - /^dependabot\/.*$/
  variables:
    VERSION_FILES: "VERSION"
  script:
  - git fetch origin main
  - |-
    if [[ -z $(git diff origin/main --name-only ${VERSION_FILES}) ]]; then
      echo "All merge requests require a version upgrade. Please update your version"
      exit 1
    fi

test:server:
  extends: .testing
  before_script:
  - cd server
  - pip install .[dev]
  script:
  - pytest tests

